export const LOGIN_PATH = "/login";
export const LOGIN_NAME = "Login";
export const WHITE_LIST = ["/login", "/404", "/401", "/register"];
export const ERROR_NAME = "ErrorPage";
export const REDIRECT_PATH = "/redirect";
export const BASE_PATH = "/";
export const REGISTER_PATH = "/register";
export const REGISTER_NAME = "Register";
export const ErrorPage = () => import("@/views/exception/404.vue");
export const Layout = () => import("@/layout/index.vue");
